language: cpp

matrix:
  include:
    - os: windows
      compiler: gcc

script:
  # Install python 3.7
  - choco install python --version=3.7.6
  - python --version

  # Build and test
  - cd Team11/Code11
  - mkdir build
  - cd build
  - cmake -A Win32 ..
  - cmake --build . --target unit_testing --config Release
  - cmake --build . --target integration_testing --config Release
  - cmake --build . --target autotester --config Release
  - cd ../../..
  - ls
  - Team11/Code11/build/src/autotester/Release/autotester Team11/Tests11/Sample_source.txt Team11/Tests11/Sample_queries.txt Team11/Tests11/out.xml > ./log.txt
  - cat ./log.txt