language: cpp

matrix:
  include:
    - os: windows
      compiler: gcc
      language: shell
      before_install:
        - choco install python --version=3.7.6
        - python -m pip install --upgrade pip
      env: PATH="/c/Python37:/c/Python37/Scripts:$PATH"

script:
  - python --version
  # Build and test
  - cd Team11/Code11
  - mkdir build
  - cd build
  - cmake -A Win32 ..
  - cmake --build . --target unit_testing --config Release
  - cmake --build . --target integration_testing --config Release
  - cmake --build . --target autotester --config Release
  # Go back to root directory and evaluate test results
  - cd ../../..
  - mkdir test_result
  - Team11/Code11/build/src/autotester/Release/autotester Team11/Tests11/Sample_source.txt Team11/Tests11/Sample_queries.txt Team11/Tests11/out.xml > ./ci_test/log.txt
  - cat ./ci_test/log.txt
  - cd ci_test
  # -p flag represents passing rate
  - python evaluate.py -p 0